-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 23:03:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TypeOfAgreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeOfAgreement` (
  `IDTypeOfAgreement` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDTypeOfAgreement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `IDEmployee` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(15) NOT NULL,
  `E-mail` VARCHAR(45) NULL,
  `Salary` FLOAT NOT NULL,
  `OvertimePay` FLOAT NULL,
  `TypeOfAgreement_IDTypeOfAgreement` INT NOT NULL,
  PRIMARY KEY (`IDEmployee`, `TypeOfAgreement_IDTypeOfAgreement`, `PhoneNumber`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC),
  UNIQUE INDEX `E-mail_UNIQUE` (`E-mail` ASC) ,
  INDEX `fk_Employee_TypeOfAgreement1_idx` (`TypeOfAgreement_IDTypeOfAgreement` ASC),
  CONSTRAINT `fk_Employee_TypeOfAgreement1`
    FOREIGN KEY (`TypeOfAgreement_IDTypeOfAgreement`)
    REFERENCES `mydb`.`TypeOfAgreement` (`IDTypeOfAgreement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `IDClient` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `E-mail` VARCHAR(45) NULL,
  `DiscountValue` INT NOT NULL,
  `Company` VARCHAR(45) NULL,
  `NIP` INT(10) NULL,
  PRIMARY KEY (`IDClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `IDOder` INT NOT NULL AUTO_INCREMENT,
  `OrderMakingData` DATETIME(6) NOT NULL,
  `Employee_ID_Employee` INT NOT NULL,
  `Client_IDClient` INT NOT NULL,
  PRIMARY KEY (`IDOder`, `Employee_ID_Employee`),
  INDEX `fk_Order_Employee_idx` (`Employee_ID_Employee` ASC) ,
  INDEX `fk_Order_Client1_idx` (`Client_IDClient` ASC) ,
  CONSTRAINT `fk_Order_Employee`
    FOREIGN KEY (`Employee_ID_Employee`)
    REFERENCES `mydb`.`Employee` (`IDEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`Client_IDClient`)
    REFERENCES `mydb`.`Client` (`IDClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `IDParentCategory` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Category_IDParentCategory` INT NOT NULL,
  PRIMARY KEY (`IDParentCategory`, `Category_IDParentCategory`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) ,
  INDEX `fk_Category_Category1_idx` (`Category_IDParentCategory` ASC) ,
  CONSTRAINT `fk_Category_Category1`
    FOREIGN KEY (`Category_IDParentCategory`)
    REFERENCES `mydb`.`Category` (`IDParentCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dish` (
  `IDDish` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `SalesPrice` FLOAT NOT NULL,
  `Category_IDParentCategory` INT NOT NULL,
  PRIMARY KEY (`IDDish`, `Category_IDParentCategory`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) ,
  INDEX `fk_Dish_Category1_idx` (`Category_IDParentCategory` ASC) ,
  CONSTRAINT `fk_Dish_Category1`
    FOREIGN KEY (`Category_IDParentCategory`)
    REFERENCES `mydb`.`Category` (`IDParentCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `iDIngredient` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UnitPrice` FLOAT NOT NULL,
  PRIMARY KEY (`iDIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IngredientUnit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IngredientUnit` (
  `IDIngredientUnit` INT NOT NULL AUTO_INCREMENT,
  `Unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDIngredientUnit`),
  UNIQUE INDEX `IDIngredientUnit_UNIQUE` (`IDIngredientUnit` ASC) ,
  UNIQUE INDEX `Unit_UNIQUE` (`Unit` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DishHasIngredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DishHasIngredients` (
  `Ingredient_iDIngredient` INT NOT NULL,
  `Dish_IDDish` INT NOT NULL,
  `IngredientAmount` INT NOT NULL,
  `IngredientUnit_IDIngredientUnit` INT NOT NULL,
  PRIMARY KEY (`Dish_IDDish`, `Ingredient_iDIngredient`, `IngredientUnit_IDIngredientUnit`),
  INDEX `fk_Ingredient_has_Dish_Dish1_idx` (`Dish_IDDish` ASC) ,
  INDEX `fk_Ingredient_has_Dish_Ingredient1_idx` (`Ingredient_iDIngredient` ASC) ,
  INDEX `fk_DishHasIngredients_IngredientUnit1_idx` (`IngredientUnit_IDIngredientUnit` ASC) ,
  CONSTRAINT `fk_DishHasIngredients_Ingredient`
    FOREIGN KEY (`Ingredient_iDIngredient`)
    REFERENCES `mydb`.`Ingredient` (`iDIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DishHasIngredients_Dish`
    FOREIGN KEY (`Dish_IDDish`)
    REFERENCES `mydb`.`Dish` (`IDDish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DishHasIngredients_IngredientUnit1`
    FOREIGN KEY (`IngredientUnit_IDIngredientUnit`)
    REFERENCES `mydb`.`IngredientUnit` (`IDIngredientUnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentMethod` (
  `IDPaymentMethod` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPaymentMethod`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `IDPayment` INT NOT NULL,
  `PaymentDate` DATETIME(6) NOT NULL,
  `PayedAmount` FLOAT NOT NULL,
  `PaymentMethod_IDPaymentMethod` INT NOT NULL,
  `Order_IDOder` INT NOT NULL,
  PRIMARY KEY (`IDPayment`, `PaymentMethod_IDPaymentMethod`, `Order_IDOder`),
  INDEX `fk_Payment_PaymentMethod1_idx` (`PaymentMethod_IDPaymentMethod` ASC) ,
  INDEX `fk_Payment_Order1_idx` (`Order_IDOder` ASC) ,
  CONSTRAINT `fk_Payment_PaymentMethod1`
    FOREIGN KEY (`PaymentMethod_IDPaymentMethod`)
    REFERENCES `mydb`.`PaymentMethod` (`IDPaymentMethod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Order1`
    FOREIGN KEY (`Order_IDOder`)
    REFERENCES `mydb`.`Order` (`IDOder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `IDCity` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDCity`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) ,
  UNIQUE INDEX `IDCity_UNIQUE` (`IDCity` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryAddress` (
  `IDDeliveryAddress` INT NOT NULL,
  `PostCode` INT(5) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `BuildingNumber` INT NOT NULL,
  `HouseNumber` INT NULL,
  `City_IDCity` INT NOT NULL,
  `Client_IDClient` INT NOT NULL,
  PRIMARY KEY (`IDDeliveryAddress`, `City_IDCity`, `Client_IDClient`),
  INDEX `fk_DeliveryAddress_City1_idx` (`City_IDCity` ASC) ,
  INDEX `fk_DeliveryAddress_Client1_idx` (`Client_IDClient` ASC) ,
  CONSTRAINT `fk_DeliveryAddress_City1`
    FOREIGN KEY (`City_IDCity`)
    REFERENCES `mydb`.`City` (`IDCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DeliveryAddress_Client1`
    FOREIGN KEY (`Client_IDClient`)
    REFERENCES `mydb`.`Client` (`IDClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeOfDelivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypeOfDelivery` (
  `IDTypeOfDelivery` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DeliveryPrice` FLOAT NOT NULL,
  PRIMARY KEY (`IDTypeOfDelivery`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) ,
  UNIQUE INDEX `IDTypeOfDelivery_UNIQUE` (`IDTypeOfDelivery` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `IDDelivery` INT NOT NULL AUTO_INCREMENT,
  `DeliveryDate` DATETIME(6) NOT NULL,
  `FullPrice` FLOAT NOT NULL,
  `TypeOfDelivery_IDTypeOfDelivery` INT NOT NULL,
  `Order_IDOder` INT NOT NULL,
  PRIMARY KEY (`IDDelivery`, `TypeOfDelivery_IDTypeOfDelivery`, `Order_IDOder`),
  UNIQUE INDEX `IDDelivery_UNIQUE` (`IDDelivery` ASC) ,
  INDEX `fk_Delivery_TypeOfDelivery1_idx` (`TypeOfDelivery_IDTypeOfDelivery` ASC) ,
  INDEX `fk_Delivery_Order1_idx` (`Order_IDOder` ASC) ,
  CONSTRAINT `fk_Delivery_TypeOfDelivery1`
    FOREIGN KEY (`TypeOfDelivery_IDTypeOfDelivery`)
    REFERENCES `mydb`.`TypeOfDelivery` (`IDTypeOfDelivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_Order1`
    FOREIGN KEY (`Order_IDOder`)
    REFERENCES `mydb`.`Order` (`IDOder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderHasDish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderHasDish` (
  `IDOrderHasDish` INT NOT NULL,
  `Dish_IDDish` INT NOT NULL,
  `Order_IDOder` INT NOT NULL,
  `DishNumber` INT NOT NULL,
  `Comment` VARCHAR(45) NULL,
  INDEX `fk_Dish_has_Order_Order1_idx` (`Order_IDOder` ASC) ,
  INDEX `fk_Dish_has_Order_Dish1_idx` (`Dish_IDDish` ASC) ,
  PRIMARY KEY (`IDOrderHasDish`, `Dish_IDDish`, `Order_IDOder`),
  UNIQUE INDEX `OrderHasDishcol_UNIQUE` (`IDOrderHasDish` ASC) ,
  CONSTRAINT `fk_Dish_has_Order_Dish1`
    FOREIGN KEY (`Dish_IDDish`)
    REFERENCES `mydb`.`Dish` (`IDDish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_has_Order_Order1`
    FOREIGN KEY (`Order_IDOder`)
    REFERENCES `mydb`.`Order` (`IDOder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
